name: PR

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - {name: 'python 3.8', python: '3.8', tox: py38}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - run: tox -e ${{ matrix.tox }}
